name: React Juicy CLI

on:
  # Trigger the lint, test, build, etc. pipelines in every branch.
  push:
    # But don't run the pipeline when only `md` files are modified.
    paths-ignore:
      - "**.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn test:unit

  build:
    needs: [lint, test-unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn build

  npm-publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - id: check
        uses: EndBug/version-check@v1

      - if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change"'

      - if: steps.check.outputs.changed == 'true'
        uses: actions/checkout@v2

      - if: steps.check.outputs.changed == 'true'
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.check.outputs.changed == 'true'
        run: yarn install --frozen-lockfile

      - if: steps.check.outputs.changed == 'true'
        run: yarn build

      - if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"

      - if: steps.check.outputs.changed == 'true'
        run: yarn publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
